# image_root: '../58/PAB/'
# test_file: '../58/PAB/annotation/test/attr.json'
image_root: '../59/MPA/'
test_file:  'testjson/test.json'
# OOD test set
#test_file: 'data/PAB/annotation/test/ucc.json'


train_file: ['toytrainjson/pair_0.json',
						 'toytrainjson/pair_1.json',
						 'toytrainjson/pair_2.json',
						 'toytrainjson/pair_3.json',
						 'toytrainjson/pair_4.json',
						 'toytrainjson/pair_5.json',
						 'toytrainjson/pair_6.json',
						 'toytrainjson/pair_7.json',
						 'toytrainjson/pair_8.json',
						 'toytrainjson/pair_9.json',
						 'toytrainjson/pair_10.json',
						 'toytrainjson/pair_11.json',
						 'toytrainjson/pair_12.json',
						 'toytrainjson/pair_13.json',
						 'toytrainjson/pair_14.json',
						 'toytrainjson/pair_15.json',
]


## Image Encoder
vision_config: 'configs/config_swinB.json'
h: 224
w: 224

## Text Encoder
text_config: 'configs/config_bert.json'
text_encoder: '../checkpoint/bert-base-uncased'


## Training
load_params: False
load_pretrained: True

max_words: 56
max_tokens: 56
eda_p: 1
erasing_p: 0.6

batch_size_train: 22 #22
batch_size_test: 22
batch_size_test_text: 150

embed_dim: 256
itc_dp: 0.5
temp: 0.07
label_smooth: 0.2

## mlm loss
mask_prob: 0.25
max_masks: 10
skipgram_prb: 0.2
skipgram_size: 3
mask_whole_word: True

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: step, lr: 1e-4, epochs: 120, num_warmup_steps: 500}

k_test: 128


be_hard: False #True
be_pose_img: False # True
pose_conv: False #True
use_yolo_gcn: True #True
yolo_weight_path: 'weights/v11_x.pt'
yolo_conf_threshold: 0.2